
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #url: jdbc:mysql://localhost:3306/lenos?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    #username: root
    #password: root
    #driver-class-name: com.mysql.jdbc.Driver
  #oracle.jdbc.OracleDriver
    #oracle版
    url: jdbc:oracle:thin:@10.160.238.13:1521:hollycrm
    username: hollycc
    password: hollycc
    driver-class-name: oracle.jdbc.OracleDriver

    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true
server:
  tomcat:
    uri-encoding: UTF-8
  port: 80
