
package com.capinfo.dcxm.dmonitor.yerss;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "A5ServerSoapService", targetNamespace = "http://webservice/", wsdlLocation = "http://172.24.198.203:8580/A5WebService/A5ServerSoapPort?wsdl")
public class A5ServerSoapService
    extends Service
{

    private final static URL A5SERVERSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException A5SERVERSOAPSERVICE_EXCEPTION;
    private final static QName A5SERVERSOAPSERVICE_QNAME = new QName("http://webservice/", "A5ServerSoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.24.198.203:8580/A5WebService/A5ServerSoapPort?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        A5SERVERSOAPSERVICE_WSDL_LOCATION = url;
        A5SERVERSOAPSERVICE_EXCEPTION = e;
    }

    public A5ServerSoapService() {
        super(__getWsdlLocation(), A5SERVERSOAPSERVICE_QNAME);
    }

    public A5ServerSoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), A5SERVERSOAPSERVICE_QNAME, features);
    }

    public A5ServerSoapService(URL wsdlLocation) {
        super(wsdlLocation, A5SERVERSOAPSERVICE_QNAME);
    }

    public A5ServerSoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, A5SERVERSOAPSERVICE_QNAME, features);
    }

    public A5ServerSoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public A5ServerSoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns A5ServerSoapDelegate
     */
    @WebEndpoint(name = "A5ServerSoapPort")
    public A5ServerSoapDelegate getA5ServerSoapPort() {
        return super.getPort(new QName("http://webservice/", "A5ServerSoapPort"), A5ServerSoapDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns A5ServerSoapDelegate
     */
    @WebEndpoint(name = "A5ServerSoapPort")
    public A5ServerSoapDelegate getA5ServerSoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "A5ServerSoapPort"), A5ServerSoapDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (A5SERVERSOAPSERVICE_EXCEPTION!= null) {
            throw A5SERVERSOAPSERVICE_EXCEPTION;
        }
        return A5SERVERSOAPSERVICE_WSDL_LOCATION;
    }

}
